[package]
name = "ruin-me-image"
version = "1.2.0"
edition = "2024"

[profile.release]
opt-level = 3
strip = true
lto = true

[dependencies]
eframe = "0.31.1"
image = "0.25.6"
rand = "0.9.1"
rand_chacha = "0.9.0"
rfd = "0.15.3"
ron = "0.10.1"
serde = { version = "1.0.219", features = ["derive"] }
