[package]
name = "ruin-me-image"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
image = "0.25.6"
rand = "0.9.1"
rand_chacha = "0.9.0"
rfd = "0.15.3"
ron = "0.10.1"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
